[build]
  args_bin = ["serve"]
  bin = "./tmp/main"
  cmd = "$(go env GOPATH)/bin/templ generate && go build -o tmp/main ./main.go"
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go", ".*_templ.go"]
  include_ext = ["go", "templ", "html"]
  # post_cmd = ["kill -15 $(lsof -ti:8080)"]

[log]
  time = false
