---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pippaothy
  labels:
    app: pippaothy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pippaothy
  template:
    metadata:
      labels:
        app: pippaothy
    spec:
      containers:
        - name: pippaothy
          image: julianone/pippaothy:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PORT
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: RESEND_API_KEY
            - name: FROM_EMAIL
              value: "noreply@pippaothy.com"
            - name: GO_ENV
              value: "production"
            - name: TLS_ENABLED
              value: "true"
          volumeMounts:
            - name: ssd-storage
              mountPath: /mnt/ssd
      volumes:
        - name: ssd-storage
          hostPath:
            path: /mnt/ssd
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: pippaothy
spec:
  selector:
    app: pippaothy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
