apiVersion: apps/v1
kind: Deployment
metadata:
  name: pippaothy
  labels:
    app: pippaothy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pippaothy
  template:
    metadata:
      labels:
        app: pippaothy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pippaothy 
spec:
  selector:
    app: pippaothy 
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 80 # Container port

